000ET2641      County of Los Angeles                                                           
000ET2641      Department of Registrar-Recorder/County Clerk                                   
000ET2641      JUNE 05, 2018 - 2018 STATEWIDE DIRECT PRIMARY ELECTION                          
000ET2641      Semi-Final Official Election Returns                                            
000TD2641      10:38 05/10/2018                                                                
001CC00  03    ASSESSOR                                                                        
001BK00  03                                                                                    
001CN00  03       JEFFREY PRANG                                                833    10.11    
001CN00  03       JOHN LOEW                                                  1,642    19.93    
001CN00  03       KRISH INDRA KUMAR                                          2,470    29.99    
001CN00  03       SANDY SUN                                                  3,292    39.97    
001BK00  03                                                                                    
001PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
001DR00  03    REGISTRATION     5,131,286                                                      
002CC00  03    GOVERNOR                                                                        
002VN00  03    VOTER NOMINATED                                                                 
002BK00  03                                                                                    
002CN00  03       JOSH JONES             GRN                                 1,161     0.26    
002CN00  03       J BRIBIESCA            DEM                                 2,304     0.52    
002CN00  03       GLORIA E LA RIVA        PF                                 3,545     0.80    
002CN00  03       PETER Y LIU            REP                                 4,681     1.06    
002CN00  03       A VILLARAIGOSA         DEM                                 5,918     1.34    
002CN00  03       YVONNE GIRARD          REP                                 7,068     1.60    
002CN00  03       ROBERT D GRIFFIS       DEM                                 8,141     1.84    
002CN00  03       SHUBHAM GOEL            NP                                 9,403     2.12    
002CN00  03       TRAVIS ALLEN           REP                                10,601     2.40    
002CN00  03       AKINYEMI AGBEDE        DEM                                11,747     2.65    
002CN00  03       JOHNNY WATTENBURG       NP                                12,805     2.89    
002CN00  03       NICKOLAS WILDSTAR      LIB                                13,933     3.15    
002CN00  03       DESMOND SILVEIRA        NP                                15,192     3.43    
002CN00  03       M SHELLENBERGER        DEM                                16,436     3.71    
002CN00  03       ZOLTAN ISTVAN          LIB                                17,560     3.97    
002CN00  03       C N CARLSON            GRN                                18,779     4.24    
002CN00  03       THOMAS J CARES         DEM                                19,782     4.47    
002CN00  03       JOHN CHIANG            DEM                                21,073     4.76    
002CN00  03       JOHN H COX             REP                                22,307     5.04    
002CN00  03       AMANDA RENTERIA        DEM                                23,414     5.29    
002CN00  03       DELAINE EASTIN         DEM                                24,732     5.59    
002CN00  03       JEFFREY E TAYLOR        NP                                25,743     5.82    
002CN00  03       KLEMENT TINAJ          DEM                                26,935     6.09    
002CN00  03       HAKAN MIKADO            NP                                28,050     6.34    
002CN00  03       ALBERT C MEZZETTI      DEM                                29,286     6.62    
002CN00  03       GAVIN NEWSOM           DEM                                30,491     6.89    
002CN00  03       R C NEWMAN II          REP                                31,520     7.12    
002BK00  03                                                                                    
002PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
002DR00  03    REGISTRATION     5,131,286                                                      
003CC00  03    LIEUTENANT GOVERNOR                                                             
003VN00  03    VOTER NOMINATED                                                                 
003BK00  03                                                                                    
003CN00  03       JEFF BLEICH            DEM                                   746     1.49    
003CN00  03       ELENI KOUNALAKIS       DEM                                 1,499     2.99    
003CN00  03       C GHARABIKLOU          DEM                                 2,297     4.59    
003CN00  03       TIM FERREIRA           LIB                                 2,994     5.98    
003CN00  03       DAVID FENNELL          REP                                 3,844     7.68    
003CN00  03       DANNY THOMAS            NP                                 4,562     9.11    
003CN00  03       COLE HARRIS            REP                                 5,297    10.58    
003CN00  03       ED HERNANDEZ           DEM                                 6,065    12.11    
003CN00  03       DAVID R HERNANDEZ      REP                                 6,880    13.74    
003CN00  03       LYDIA ORTEGA           REP                                 7,585    15.15    
003CN00  03       GAYLE MCLAUGHLIN        NP                                 8,297    16.57    
003BK00  03                                                                                    
003PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
003DR00  03    REGISTRATION     5,131,286                                                      
004CC00  03    SECRETARY OF STATE                                                              
004VN00  03    VOTER NOMINATED                                                                 
004BK00  03                                                                                    
004CN00  03       ALEX PADILLA           DEM                                   488     2.82    
004CN00  03       GAIL K LIGHTFOOT       LIB                                   954     5.50    
004CN00  03       C.T. WEBER              PF                                 1,467     8.46    
004CN00  03       ERIK RYDBERG           GRN                                 1,880    10.85    
004CN00  03       RAUL RODRIGUEZ JR      REP                                 2,432    14.03    
004CN00  03       MICHAEL FEINSTEIN      GRN                                 2,894    16.70    
004CN00  03       RUBEN MAJOR            DEM                                 3,359    19.38    
004CN00  03       MARK P MEUSER          REP                                 3,859    22.26    
004BK00  03                                                                                    
004PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
004DR00  03    REGISTRATION     5,131,286                                                      
005CC00  03    CONTROLLER                                                                      
005VN00  03    VOTER NOMINATED                                                                 
005BK00  03                                                                                    
005CN00  03       K RODITIS              REP                                    73    17.30    
005CN00  03       MARY LOU FINLEY         PF                                   147    34.83    
005CN00  03       BETTY T YEE            DEM                                   202    47.87    
005BK00  03                                                                                    
005PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
005DR00  03    REGISTRATION     5,131,286                                                      
006CC00  03    TREASURER                                                                       
006VN00  03    VOTER NOMINATED                                                                 
006BK00  03                                                                                    
006CN00  03       VIVEK VISWANATHAN      DEM                                   254     6.99    
006CN00  03       JACK M GUERRERO        REP                                   468    12.88    
006CN00  03       KEVIN AKIN              PF                                   737    20.28    
006CN00  03       GREG CONLON            REP                                   949    26.11    
006CN00  03       FIONA MA               DEM                                 1,226    33.74    
006BK00  03                                                                                    
006PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
006DR00  03    REGISTRATION     5,131,286                                                      
007CC00  03    ATTORNEY GENERAL                                                                
007VN00  03    VOTER NOMINATED                                                                 
007BK00  03                                                                                    
007CN00  03       DAVE JONES             DEM                                   240    10.70    
007CN00  03       STEVEN C BAILEY        REP                                   434    19.34    
007CN00  03       XAVIER BECERRA         DEM                                   677    30.17    
007CN00  03       ERIC EARLY             REP                                   893    39.80    
007BK00  03                                                                                    
007PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
007DR00  03    REGISTRATION     5,131,286                                                      
008CC00  03    INSURANCE COMMISSIONER                                                          
008VN00  03    VOTER NOMINATED                                                                 
008BK00  03                                                                                    
008CN00  03       STEVE POIZNER           NP                                   240    10.70    
008CN00  03       RICARDO LARA           DEM                                   434    19.34    
008CN00  03       NATHALIE HRIZI          PF                                   677    30.17    
008CN00  03       ASIF MAHMOOD           DEM                                   893    39.80    
008BK00  03                                                                                    
008PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
008DR00  03    REGISTRATION     5,131,286                                                      
009CC07  03    MEMBER STATE BOARD OF        EQUALIZATION-3RD DISTRICT                          
009VN07  03    VOTER NOMINATED                                                                 
009BK07  03                                                                                    
009CN07  03       BEN PAK                DEM                                   411     2.69    
009CN07  03       NANCY PEARLMAN         DEM                                   870     5.69    
009CN07  03       DOUG KRIEGEL           DEM                                 1,271     8.31    
009CN07  03       TONY VAZQUEZ           DEM                                 1,680    10.99    
009CN07  03       SCOTT SVONKIN          DEM                                 2,143    14.01    
009CN07  03       CHERYL C TURNER        DEM                                 2,516    16.45    
009CN07  03       MICHEAL O'LEARY         NP                                 2,966    19.40    
009CN07  03       G RICK MARSHALL        REP                                 3,434    22.46    
009BK07  03                                                                                    
009PR07  03    TOTAL PRECINCTS      3,784            PRECINCTS REPORTING     3,784      100    
009DR07  03    REGISTRATION     4,431,999                                                      
010CC07  01    MEMBER STATE BOARD OF        EQUALIZATION-1ST DISTRICT                          
010VN07  01    VOTER NOMINATED                                                                 
010BK07  01                                                                                    
010CN07  01       TED GAINES             REP                                   247    10.47    
010CN07  01       CONNIE CONWAY          REP                                   459    19.47    
010CN07  01       DAVID EVANS            REP                                   720    30.53    
010CN07  01       TOM HALLINAN           DEM                                   932    39.53    
010BK07  01                                                                                    
010PR07  01    TOTAL PRECINCTS        573            PRECINCTS REPORTING       573      100    
010DR07  01    REGISTRATION       699,287                                                      
011CC00  03    UNITED STATES SENATOR                                                           
011VN00  03    VOTER NOMINATED                                                                 
011BK00  03                                                                                    
011CN00  03       GERALD PLUMMER         DEM                                 1,176     0.19    
011CN00  03       TOM PALZER             REP                                 2,333     0.37    
011CN00  03       JOHN T PARKER           PF                                 3,595     0.57    
011CN00  03       DOUGLAS H PIERCE       DEM                                 4,743     0.76    
011CN00  03       HERBERT G PETERS       DEM                                 5,988     0.96    
011CN00  03       JAMES P BRADLEY        REP                                 7,158     1.14    
011CN00  03       ARUN K BHUMITRA        REP                                 8,250     1.32    
011CN00  03       JERRY JOSEPH LAWS      REP                                 9,523     1.52    
011CN00  03       PATRICK LITTLE         REP                                10,742     1.72    
011CN00  03       TIM GILDERSLEEVE        NP                                11,898     1.90    
011CN00  03       MICHAEL F GIRGIS        NP                                12,979     2.07    
011CN00  03       DON J GRUNDMANN         NP                                14,120     2.26    
011CN00  03       RASH BIHARI GHOSH       NP                                15,393     2.46    
011CN00  03       LING LING SHI           NP                                16,651     2.66    
011CN00  03       JOHN CREW              REP                                17,786     2.84    
011CN00  03       ERIN CRUZ              REP                                19,016     3.04    
011CN00  03       DERRICK M REID         LIB                                20,034     3.20    
011CN00  03       DIANNE FEINSTEIN       DEM                                21,353     3.41    
011CN00  03       COLLEEN S FERNALD       NP                                22,599     3.61    
011CN00  03       ADRIENNE N EDWARDS     DEM                                23,710     3.79    
011CN00  03       PAUL A TAYLOR          REP                                25,047     4.00    
011CN00  03       DONNIE O TURNER        DEM                                26,090     4.17    
011CN00  03       PAT HARRIS             DEM                                27,289     4.36    
011CN00  03       ALISON HARTSON         DEM                                28,443     4.55    
011CN00  03       JASON M HANANIA         NP                                29,661     4.74    
011CN00  03       DAVID HILDEBRAND       DEM                                30,888     4.94    
011CN00  03       LEE OLSON               NP                                31,919     5.10    
011CN00  03       ROQUE DE LA FUENTE     REP                                33,186     5.30    
011CN00  03       KEVIN DE LEON          DEM                                34,365     5.49    
011CN00  03       KEVIN MOTTUS           REP                                35,458     5.67    
011CN00  03       DAVID MOORE             NP                                36,697     5.86    
011CN00  03       MARIO NABLIBA          REP                                37,690     6.02    
011BK00  03                                                                                    
011PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
011DR00  03    REGISTRATION     5,131,286                                                      
012CC02  23    U.S. REPRESENTATIVE          23RD DISTRICT                                      
012VN02  23    VOTER NOMINATED                                                                 
012BK02  23                                                                                    
012CN02  23       MARY HELEN BARRO       DEM                                    63     4.90    
012CN02  23       KURTIS WILSON          DEM                                   127     9.88    
012CN02  23       WENDY REED             DEM                                   176    13.70    
012CN02  23       JAMES DAVIS             NP                                   249    19.38    
012CN02  23       TATIANA MATTA          DEM                                   307    23.89    
012CN02  23       KEVIN MCCARTHY         REP                                   363    28.25    
012BK02  23                                                                                    
012PR02  23    TOTAL PRECINCTS         31            PRECINCTS REPORTING        31      100    
012DR02  23    REGISTRATION        40,756                                                      
013CC02  25    U.S. REPRESENTATIVE          25TH DISTRICT                                      
013VN02  25    VOTER NOMINATED                                                                 
013BK02  25                                                                                    
013CN02  25       MARY PALLANT           DEM                                   252     6.60    
013CN02  25       JESS P PHOENIX         DEM                                   514    13.46    
013CN02  25       STEVE KNIGHT           REP                                   764    20.01    
013CN02  25       BRYAN CAFORIO          DEM                                 1,047    27.42    
013CN02  25       KATIE HILL             DEM                                 1,242    32.52    
013BK02  25                                                                                    
013PR02  25    TOTAL PRECINCTS        251            PRECINCTS REPORTING       251      100    
013DR02  25    REGISTRATION       314,314                                                      
014CC02  26    U.S. REPRESENTATIVE          26TH DISTRICT                                      
014VN02  26    VOTER NOMINATED                                                                 
014BK02  26                                                                                    
014CN02  26       JULIA BROWNLEY         DEM                                    13    10.57    
014CN02  26       JEFFREY D BURUM        REP                                    26    21.14    
014CN02  26       ANTONIO SABATO JR      REP                                    32    26.02    
014CN02  26       JOHN NELSON            DEM                                    52    42.28    
014BK02  26                                                                                    
014PR02  26    TOTAL PRECINCTS          6            PRECINCTS REPORTING         6      100    
014DR02  26    REGISTRATION         5,963                                                      
015CC02  27    U.S. REPRESENTATIVE          27TH DISTRICT                                      
015VN02  27    VOTER NOMINATED                                                                 
015BK02  27                                                                                    
015CN02  27       BRYAN WITT             DEM                                    21    36.21    
015CN02  27       JUDY CHU               DEM                                    37    63.79    
015BK02  27                                                                                    
015PR02  27    TOTAL PRECINCTS        309            PRECINCTS REPORTING       309      100    
015DR02  27    REGISTRATION       353,781                                                      
016CC02  28    U.S. REPRESENTATIVE          28TH DISTRICT                                      
016VN02  28    VOTER NOMINATED                                                                 
016BK02  28                                                                                    
016CN02  28       SAL GENOVESE           DEM                                    10    13.89    
016CN02  28       ADAM B SCHIFF          DEM                                    24    33.33    
016CN02  28       J J NALBANDIAN         REP                                    38    52.78    
016BK02  28                                                                                    
016PR02  28    TOTAL PRECINCTS        332            PRECINCTS REPORTING       332      100    
016DR02  28    REGISTRATION       427,358                                                      
017CC02  29    U.S. REPRESENTATIVE          29TH DISTRICT                                      
017VN02  29    VOTER NOMINATED                                                                 
017BK02  29                                                                                    
017CN02  29       BENITO B BERNAL        REP                                   278     6.56    
017CN02  29       JOSEPH SHAMMAS         DEM                                   541    12.77    
017CN02  29       TONY CARDENAS          DEM                                   863    20.37    
017CN02  29       JUAN REY                NP                                 1,116    26.34    
017CN02  29       ANGELICA M DUENAS      GRN                                 1,439    33.96    
017BK02  29                                                                                    
017PR02  29    TOTAL PRECINCTS        238            PRECINCTS REPORTING       238      100    
017DR02  29    REGISTRATION       314,891                                                      
018CC02  30    U.S. REPRESENTATIVE          30TH DISTRICT                                      
018VN02  30    VOTER NOMINATED                                                                 
018BK02  30                                                                                    
018CN02  30       JON PELZER             DEM                                    37     9.61    
018CN02  30       BRAD SHERMAN           DEM                                    77     20.0    
018CN02  30       RAJI RAB               DEM                                   127    32.99    
018CN02  30       MARK S REED            REP                                   144    37.40    
018BK02  30                                                                                    
018PR02  30    TOTAL PRECINCTS        317            PRECINCTS REPORTING       317      100    
018DR02  30    REGISTRATION       427,723                                                      
019CC02  32    U.S. REPRESENTATIVE          32ND DISTRICT                                      
019VN02  32    VOTER NOMINATED                                                                 
019BK02  32                                                                                    
019CN02  32       GRACE F NAPOLITANO     DEM                                     2      100    
019BK02  32                                                                                    
019PR02  32    TOTAL PRECINCTS        284            PRECINCTS REPORTING       284      100    
019DR02  32    REGISTRATION       320,115                                                      
020CC02  33    U.S. REPRESENTATIVE          33RD DISTRICT                                      
020VN02  33    VOTER NOMINATED                                                                 
020BK02  33                                                                                    
020CN02  33       TED W LIEU             DEM                                    96    16.08    
020CN02  33       KENNETH W WRIGHT       REP                                   202    33.84    
020CN02  33       EMORY P RODGERS        DEM                                   299    50.08    
020BK02  33                                                                                    
020PR02  33    TOTAL PRECINCTS        423            PRECINCTS REPORTING       423      100    
020DR02  33    REGISTRATION       472,510                                                      
021CC02  34    U.S. REPRESENTATIVE          34TH DISTRICT                                      
021VN02  34    VOTER NOMINATED                                                                 
021BK02  34                                                                                    
021CN02  34       JIMMY GOMEZ            DEM                                   325    16.92    
021CN02  34       ANGELA E MCARDLE       LIB                                   644    33.52    
021CN02  34       KENNETH MEJIA          GRN                                   952    49.56    
021BK02  34                                                                                    
021PR02  34    TOTAL PRECINCTS        234            PRECINCTS REPORTING       234      100    
021DR02  34    REGISTRATION       303,957                                                      
022CC02  35    U.S. REPRESENTATIVE          35TH DISTRICT                                      
022VN02  35    VOTER NOMINATED                                                                 
022BK02  35                                                                                    
022CN02  35       JOE BACA               DEM                                    99    16.64    
022CN02  35       C L VALIENTE           REP                                   196    32.94    
022CN02  35       NORMA J TORRES         DEM                                   300    50.42    
022BK02  35                                                                                    
022PR02  35    TOTAL PRECINCTS         51            PRECINCTS REPORTING        51      100    
022DR02  35    REGISTRATION        61,237                                                      
023CC02  37    U.S. REPRESENTATIVE          37TH DISTRICT                                      
023VN02  37    VOTER NOMINATED                                                                 
023BK02  37                                                                                    
023CN02  37       KAREN BASS             DEM                                     5    33.33    
023CN02  37       RON J BASSILIAN        REP                                    10    66.67    
023BK02  37                                                                                    
023PR02  37    TOTAL PRECINCTS        357            PRECINCTS REPORTING       357      100    
023DR02  37    REGISTRATION       417,362                                                      
024CC02  38    U.S. REPRESENTATIVE          38TH DISTRICT                                      
024VN02  38    VOTER NOMINATED                                                                 
024BK02  38                                                                                    
024CN02  38       LINDA T SANCHEZ        DEM                                    27    38.57    
024CN02  38       RYAN DOWNING           REP                                    43    61.43    
024BK02  38                                                                                    
024PR02  38    TOTAL PRECINCTS        335            PRECINCTS REPORTING       335      100    
024DR02  38    REGISTRATION       352,949                                                      
025CC02  39    U.S. REPRESENTATIVE          39TH DISTRICT                                      
025VN02  39    VOTER NOMINATED                                                                 
025BK02  39                                                                                    
025CN02  39       SAM JAMMAL             DEM                                    37     0.62    
025CN02  39       PHIL LIBERATORE        REP                                    79     1.33    
025CN02  39       SUZI PARK LEGGETT      DEM                                   123     2.06    
025CN02  39       HERBERT H LEE          DEM                                   149     2.50    
025CN02  39       YOUNG KIM              REP                                   203     3.41    
025CN02  39       STEVEN C VARGAS        REP                                   234     3.93    
025CN02  39       TED M ALEMAYHU          AI                                   286     4.80    
025CN02  39       SOPHIA J ALEXANDER      AI                                   312     5.23    
025CN02  39       ANDREW SAREGA          REP                                   340     5.70    
025CN02  39       KAREN LEE SCHATZLE      NP                                   387     6.49    
025CN02  39       GIL CISNEROS           DEM                                   439     7.36    
025CN02  39       STEVE COX               NP                                   472     7.92    
025CN02  39       JOHN J CULLUM          REP                                   487     8.17    
025CN02  39       MAI KHANH TRAN         DEM                                   534     8.96    
025CN02  39       ANDY THORBURN          DEM                                   585     9.81    
025CN02  39       BOB HUFF               REP                                   639    10.72    
025CN02  39       SHAWN NELSON           REP                                   655    10.99    
025BK02  39                                                                                    
025PR02  39    TOTAL PRECINCTS         94            PRECINCTS REPORTING        94      100    
025DR02  39    REGISTRATION        99,491                                                      
026CC02  40    U.S. REPRESENTATIVE          40TH DISTRICT                                      
026VN02  40    VOTER NOMINATED                                                                 
026BK02  40                                                                                    
026CN02  40       R CORTES BARRAGAN      GRN                                    96    33.10    
026CN02  40       L ROYBAL-ALLARD        DEM                                   194    66.90    
026BK02  40                                                                                    
026PR02  40    TOTAL PRECINCTS        240            PRECINCTS REPORTING       240      100    
026DR02  40    REGISTRATION       273,579                                                      
027CC02  43    U.S. REPRESENTATIVE          43RD DISTRICT                                      
027VN02  43    VOTER NOMINATED                                                                 
027BK02  43                                                                                    
027CN02  43       MAXINE WATERS          DEM                                   173     6.36    
027CN02  43       MIGUEL A ZUNIGA        GRN                                   368    13.54    
027CN02  43       FRANK T DEMARTINI      REP                                   561    20.64    
027CN02  43       EDWIN P DUTERTE        REP                                   711    26.16    
027CN02  43       OMAR NAVARRO           REP                                   905    33.30    
027BK02  43                                                                                    
027PR02  43    TOTAL PRECINCTS        339            PRECINCTS REPORTING       339      100    
027DR02  43    REGISTRATION       368,176                                                      
028CC02  44    U.S. REPRESENTATIVE          44TH DISTRICT                                      
028VN02  44    VOTER NOMINATED                                                                 
028BK02  44                                                                                    
028CN02  44       NANETTE D BARRAGAN     DEM                                    94    10.43    
028CN02  44       AJA L BROWN            DEM                                   182    20.20    
028CN02  44       JAZMINA SAAVEDRA       REP                                   272    30.19    
028CN02  44       STACEY DASH            REP                                   353    39.18    
028BK02  44                                                                                    
028PR02  44    TOTAL PRECINCTS        314            PRECINCTS REPORTING       314      100    
028DR02  44    REGISTRATION       336,551                                                      
029CC02  47    U.S. REPRESENTATIVE          47TH DISTRICT                                      
029VN02  47    VOTER NOMINATED                                                                 
029BK02  47                                                                                    
029CN02  47       JOHN BRISCOE           REP                                    11    18.64    
029CN02  47       ALAN LOWENTHAL         DEM                                    17    28.81    
029CN02  47       DAVID M CLIFFORD       REP                                    31    52.54    
029BK02  47                                                                                    
029PR02  47    TOTAL PRECINCTS        202            PRECINCTS REPORTING       202      100    
029DR02  47    REGISTRATION       240,573                                                      
030CC03  18    STATE SENATOR                18TH DISTRICT                                      
030VN03  18    VOTER NOMINATED                                                                 
030BK03  18                                                                                    
030CN03  18       BRANDON SAARIO         REP                                     6    13.04    
030CN03  18       ROGER JAMES SAYEGH     DEM                                     9    19.57    
030CN03  18       BOB HERTZBERG          DEM                                    11    23.91    
030CN03  18       RUDY MELENDEZ          REP                                    20    43.48    
030BK03  18                                                                                    
030PR03  18    TOTAL PRECINCTS        357            PRECINCTS REPORTING       357      100    
030DR03  18    REGISTRATION       466,311                                                      
031CC03  22    STATE SENATOR                22ND DISTRICT                                      
031VN03  22    VOTER NOMINATED                                                                 
031BK03  22                                                                                    
031CN03  22       MONICA GARCIA          DEM                                   229     9.92    
031CN03  22       RUBEN SIERRA           DEM                                   474    20.54    
031CN03  22       SUSAN RUBIO            DEM                                   703    30.46    
031CN03  22       MIKE ENG               DEM                                   902    39.08    
031BK03  22                                                                                    
031PR03  22    TOTAL PRECINCTS        371            PRECINCTS REPORTING       371      100    
031DR03  22    REGISTRATION       404,957                                                      
032CC03  24    STATE SENATOR                24TH DISTRICT                                      
032VN03  24    VOTER NOMINATED                                                                 
032BK03  24                                                                                    
032CN03  24       PETER CHOI             DEM                                    21    35.59    
032CN03  24       MARIA ELENA DURAZO     DEM                                    38    64.41    
032BK03  24                                                                                    
032PR03  24    TOTAL PRECINCTS        320            PRECINCTS REPORTING       320      100    
032DR03  24    REGISTRATION       411,253                                                      
033CC03  26    STATE SENATOR                26TH DISTRICT                                      
033VN03  26    VOTER NOMINATED                                                                 
033BK03  26                                                                                    
033CN03  26       BARON BRUNO             NP                                    34    14.98    
033CN03  26       BEN ALLEN              DEM                                    75    33.04    
033CN03  26       MARK MATTHEW HERD      LIB                                   118    51.98    
033BK03  26                                                                                    
033PR03  26    TOTAL PRECINCTS        543            PRECINCTS REPORTING       543      100    
033DR03  26    REGISTRATION       625,544                                                      
034CC03  30    STATE SENATOR                30TH DISTRICT                                      
034VN03  30    VOTER NOMINATED                                                                 
034BK03  30                                                                                    
034CN03  30       HOLLY J MITCHELL       DEM                                    43      100    
034BK03  30                                                                                    
034PR03  30    TOTAL PRECINCTS        430            PRECINCTS REPORTING       430      100    
034DR03  30    REGISTRATION       504,141                                                      
035CC03  32    STATE SENATOR                32ND DISTRICT                                      
035VN03  32    VOTER NOMINATED                                                                 
035BK03  32                                                                                    
035CN03  32       BOB J ARCHULETA        DEM                                    70     1.97    
035CN03  32       RUDY BERMUDEZ          DEM                                   144     4.04    
035CN03  32       ION SAREGA             REP                                   187     5.25    
035CN03  32       VICKY SANTANA          DEM                                   272     7.64    
035CN03  32       VIVIAN ROMERO          DEM                                   320     8.99    
035CN03  32       ALI S TAJ              DEM                                   380    10.67    
035CN03  32       RITA TOPALIAN          REP                                   457    12.84    
035CN03  32       DAVID CASTELLANOS      DEM                                   493    13.85    
035CN03  32       TONY MENDOZA           DEM                                   597    16.77    
035CN03  32       VANESSA DELGADO        DEM                                   640    17.98    
035BK03  32                                                                                    
035PR03  32    TOTAL PRECINCTS        421            PRECINCTS REPORTING       421      100    
035DR03  32    REGISTRATION       449,759                                                      
036CC03  34    STATE SENATOR                34TH DISTRICT                                      
036VN03  34    VOTER NOMINATED                                                                 
036BK03  34                                                                                    
036CN03  34       JESTIN L SAMSON        DEM                                     1     3.45    
036CN03  34       AKASH A HAWKINS        DEM                                     6    20.69    
036CN03  34       TOM UMBERG             DEM                                     9    31.03    
036CN03  34       JANET NGUYEN           REP                                    13    44.83    
036BK03  34                                                                                    
036PR03  34    TOTAL PRECINCTS         34            PRECINCTS REPORTING        34      100    
036DR03  34    REGISTRATION        44,278                                                      
037MC03  29    SENATE DISTRICT 29           RECALL MEASURE                                     
037VN03  29    VOTER NOMINATED                                                                 
037BK03  29                                                                                    
037MT03  29         JN - RECALL OF JOSH NEWMAN      - YES                       58    32.95    
037MT03  29              (MAJORITY OF VOTES CAST)   - NO                       118    67.05    
037BK03  29                                                                                    
037PR03  29    TOTAL PRECINCTS         80            PRECINCTS REPORTING        80      100    
037DR03  29    REGISTRATION        82,029                                                      
038CC03  20    STATE SENATOR                20TH DISTRICT                                      
038VN03  20    VOTER NOMINATED                                                                 
038BK03  20                                                                                    
038CN03  20       PAUL VINCENT AVILA     DEM                                   106    16.88    
038CN03  20       MATTHEW MUNSON         REP                                   205    32.64    
038CN03  20       CONNIE LEYVA           DEM                                   317    50.48    
038BK03  20                                                                                    
038PR03  20    TOTAL PRECINCTS         53            PRECINCTS REPORTING        53      100    
038DR03  20    REGISTRATION        61,537                                                      
039CC03  29    SENATE DISTRICT 29           SPECIAL RECALL ELECTION                            
039VN03  29    VOTER NOMINATED                                                                 
039BK03  29                                                                                    
039CN03  29       KEVIN CARR             DEM                                    58     4.40    
039CN03  29       JOSEPH CHO             DEM                                   118     8.95    
039CN03  29       LING LING CHANG        REP                                   197    14.94    
039CN03  29       BRUCE WHITAKER         REP                                   244    18.50    
039CN03  29       JOSH FERGUSON          DEM                                   330    25.02    
039CN03  29       GEORGE C. SHEN         REP                                   372    28.20    
039BK03  29                                                                                    
039PR03  29    TOTAL PRECINCTS         80            PRECINCTS REPORTING        80      100    
039DR03  29    REGISTRATION        82,029                                                      
040CC03  32    STATE SENATOR                32ND DIST TERM ENDS 12/18                          
040VN03  32    VOTER NOMINATED                                                                 
040BK03  32                                                                                    
040CN03  32       TONY MENDOZA           DEM                                    70     1.64    
040CN03  32       ALI S TAJ              DEM                                   144     3.36    
040CN03  32       RITA TOPALIAN          REP                                   187     4.37    
040CN03  32       JOHN PAUL DRAYER       DEM                                   272     6.36    
040CN03  32       VANESSA DELGADO        DEM                                   320     7.48    
040CN03  32       DARREN J GENDRON       DEM                                   380     8.88    
040CN03  32       BOB J ARCHULETA        DEM                                   457    10.68    
040CN03  32       VICKY SANTANA          DEM                                   493    11.52    
040CN03  32       ION SAREGA             REP                                   597    13.95    
040CN03  32       VIVIAN ROMERO          DEM                                   640    14.95    
040CN03  32       RUDY BERMUDEZ          DEM                                   720    16.82    
040BK03  32                                                                                    
040PR03  32    TOTAL PRECINCTS        421            PRECINCTS REPORTING       421      100    
040DR03  32    REGISTRATION       449,759                                                      
041CC04  36    MEMBER OF THE ASSEMBLY       36TH DISTRICT                                      
041VN04  36    VOTER NOMINATED                                                                 
041BK04  36                                                                                    
041CN04  36       STEVE FOX              DEM                                    75    33.48    
041CN04  36       TOM LACKEY             REP                                   149    66.52    
041BK04  36                                                                                    
041PR04  36    TOTAL PRECINCTS        162            PRECINCTS REPORTING       162      100    
041DR04  36    REGISTRATION       196,242                                                      
042CC04  38    MEMBER OF THE ASSEMBLY       38TH DISTRICT                                      
042VN04  38    VOTER NOMINATED                                                                 
042BK04  38                                                                                    
042CN04  38       DANTE ACOSTA           REP                                   233    33.48    
042CN04  38       CHRISTY SMITH          DEM                                   463    66.52    
042BK04  38                                                                                    
042PR04  38    TOTAL PRECINCTS        158            PRECINCTS REPORTING       158      100    
042DR04  38    REGISTRATION       208,059                                                      
043CC04  39    MEMBER OF THE ASSEMBLY       39TH DISTRICT                                      
043VN04  39    VOTER NOMINATED                                                                 
043BK04  39                                                                                    
043CN04  39       PATREA PATRICK         DEM                                   165     5.02    
043CN04  39       RICARDO A BENITEZ      REP                                   288     8.75    
043CN04  39       PATTY LOPEZ            DEM                                   481    14.62    
043CN04  39       ANTONIO SANCHEZ        DEM                                   611    18.57    
043CN04  39       BONNIE CORWIN          DEM                                   795    24.16    
043CN04  39       LUZ MARIA RIVAS        DEM                                   950    28.88    
043BK04  39                                                                                    
043PR04  39    TOTAL PRECINCTS        173            PRECINCTS REPORTING       173      100    
043DR04  39    REGISTRATION       225,672                                                      
044CC04  41    MEMBER OF THE ASSEMBLY       41ST DISTRICT                                      
044VN04  41    VOTER NOMINATED                                                                 
044BK04  41                                                                                    
044CN04  41       CHRIS HOLDEN           DEM                                    20    17.24    
044CN04  41       KENNETH ROTTER         DEM                                    37    31.90    
044CN04  41       ALAN S REYNOLDS         NP                                    59    50.86    
044BK04  41                                                                                    
044PR04  41    TOTAL PRECINCTS        172            PRECINCTS REPORTING       172      100    
044DR04  41    REGISTRATION       223,883                                                      
045CC04  43    MEMBER OF THE ASSEMBLY       43RD DISTRICT                                      
045VN04  43    VOTER NOMINATED                                                                 
045BK04  43                                                                                    
045CN04  43       LAURA FRIEDMAN         DEM                                    51      100    
045BK04  43                                                                                    
045PR04  43    TOTAL PRECINCTS        213            PRECINCTS REPORTING       213      100    
045DR04  43    REGISTRATION       278,093                                                      
046CC04  45    MEMBER OF THE ASSEMBLY       45TH DISTRICT                                      
046VN04  45    VOTER NOMINATED                                                                 
046BK04  45                                                                                    
046CN04  45       JEFF BORNSTEIN         DEM                                    46     3.44    
046CN04  45       RAY BISHOP             DEM                                    98     7.33    
046CN04  45       DANIEL BRIN            DEM                                   148    11.07    
046CN04  45       JESSE GABRIEL          DEM                                   185    13.84    
046CN04  45       T ROBBINS KASSON       DEM                                   248    18.55    
046CN04  45       ANKUR PATEL            DEM                                   265    19.82    
046CN04  45       JUSTIN M CLARK         REP                                   347    25.95    
046BK04  45                                                                                    
046PR04  45    TOTAL PRECINCTS        191            PRECINCTS REPORTING       191      100    
046DR04  45    REGISTRATION       264,705                                                      
047CC04  46    MEMBER OF THE ASSEMBLY       46TH DISTRICT                                      
047VN04  46    VOTER NOMINATED                                                                 
047BK04  46                                                                                    
047CN04  46       ROXANNE B HOGE         REP                                   152    32.41    
047CN04  46       ADRIN NAZARIAN         DEM                                   317    67.59    
047BK04  46                                                                                    
047PR04  46    TOTAL PRECINCTS        192            PRECINCTS REPORTING       192      100    
047DR04  46    REGISTRATION       242,502                                                      
048CC04  48    MEMBER OF THE ASSEMBLY       48TH DISTRICT                                      
048VN04  48    VOTER NOMINATED                                                                 
048BK04  48                                                                                    
048CN04  48       BLANCA E RUBIO         DEM                                   227      100    
048BK04  48                                                                                    
048PR04  48    TOTAL PRECINCTS        197            PRECINCTS REPORTING       197      100    
048DR04  48    REGISTRATION       215,223                                                      
049CC04  49    MEMBER OF THE ASSEMBLY       49TH DISTRICT                                      
049VN04  49    VOTER NOMINATED                                                                 
049BK04  49                                                                                    
049CN04  49       BURTON BRINK           REP                                   147    34.11    
049CN04  49       ED CHAU                DEM                                   284    65.89    
049BK04  49                                                                                    
049PR04  49    TOTAL PRECINCTS        180            PRECINCTS REPORTING       180      100    
049DR04  49    REGISTRATION       204,101                                                      
050CC04  50    MEMBER OF THE ASSEMBLY       50TH DISTRICT                                      
050VN04  50    VOTER NOMINATED                                                                 
050BK04  50                                                                                    
050CN04  50       RICHARD BLOOM          DEM                                   193      100    
050BK04  50                                                                                    
050PR04  50    TOTAL PRECINCTS        289            PRECINCTS REPORTING       289      100    
050DR04  50    REGISTRATION       324,275                                                      
051CC04  51    MEMBER OF THE ASSEMBLY       51ST DISTRICT                                      
051VN04  51    VOTER NOMINATED                                                                 
051BK04  51                                                                                    
051CN04  51       WENDY CARRILLO         DEM                                    56      100    
051BK04  51                                                                                    
051PR04  51    TOTAL PRECINCTS        187            PRECINCTS REPORTING       187      100    
051DR04  51    REGISTRATION       221,161                                                      
052CC04  52    MEMBER OF THE ASSEMBLY       52ND DISTRICT                                      
052VN04  52    VOTER NOMINATED                                                                 
052BK04  52                                                                                    
052CN04  52       BEN W GIBBINS          LIB                                   106    10.34    
052CN04  52       FRANK C GUZMAN         DEM                                   205     20.0    
052CN04  52       TONI HOLLE             REP                                   317    30.93    
052CN04  52       FREDDIE RODRIGUEZ      DEM                                   397    38.73    
052BK04  52                                                                                    
052PR04  52    TOTAL PRECINCTS         53            PRECINCTS REPORTING        53      100    
052DR04  52    REGISTRATION        61,537                                                      
053CC04  53    MEMBER OF THE ASSEMBLY       53RD DISTRICT                                      
053VN04  53    VOTER NOMINATED                                                                 
053BK04  53                                                                                    
053CN04  53       KEVIN H JANG           DEM                                    75     9.07    
053CN04  53       MICHAEL A LEWIS        LIB                                   162    19.59    
053CN04  53       MIGUEL SANTIAGO        DEM                                   244    29.50    
053CN04  53       RAE E HENRY            DEM                                   346    41.84    
053BK04  53                                                                                    
053PR04  53    TOTAL PRECINCTS        132            PRECINCTS REPORTING       132      100    
053DR04  53    REGISTRATION       180,784                                                      
054CC04  54    MEMBER OF THE ASSEMBLY       54TH DISTRICT                                      
054VN04  54    VOTER NOMINATED                                                                 
054BK04  54                                                                                    
054CN04  54       TEPRING M PIQUADO      DEM                                    53     4.23    
054CN04  54       LAMAR LYONS            DEM                                   121     9.66    
054CN04  54       SYDNEY K KAMLAGER      DEM                                   184    14.70    
054CN04  54       GLEN RATCLIFF          REP                                   247    19.73    
054CN04  54       BREON D HOLLIE         DEM                                   298    23.80    
054CN04  54       STEVE DUNWOODY         DEM                                   349    27.88    
054BK04  54                                                                                    
054PR04  54    TOTAL PRECINCTS        248            PRECINCTS REPORTING       248      100    
054DR04  54    REGISTRATION       291,706                                                      
055CC04  55    MEMBER OF THE ASSEMBLY       55TH DISTRICT                                      
055VN04  55    VOTER NOMINATED                                                                 
055BK04  55                                                                                    
055CN04  55       MELISSA FAZLI          DEM                                    58     6.12    
055CN04  55       GREGG D FRITCHLE       DEM                                   118    12.46    
055CN04  55       JAMES G GERBUS         REP                                   197    20.80    
055CN04  55       PHILLIP CHEN           REP                                   244    25.77    
055CN04  55       SCOTT LEBDA            REP                                   330    34.85    
055BK04  55                                                                                    
055PR04  55    TOTAL PRECINCTS         79            PRECINCTS REPORTING        79      100    
055DR04  55    REGISTRATION        82,028                                                      
056CC04  57    MEMBER OF THE ASSEMBLY       57TH DISTRICT                                      
056VN04  57    VOTER NOMINATED                                                                 
056BK04  57                                                                                    
056CN04  57       OSCAR J LLAMAS         REP                                   147     6.96    
056CN04  57       JUSTIN J VALERO        DEM                                   293    13.87    
056CN04  57       IAN C CALDERON         DEM                                   389    18.42    
056CN04  57       BLAKE CARTER           DEM                                   584    27.65    
056CN04  57       JESSICA MARTINEZ       REP                                   699    33.10    
056BK04  57                                                                                    
056PR04  57    TOTAL PRECINCTS        226            PRECINCTS REPORTING       226      100    
056DR04  57    REGISTRATION       232,278                                                      
057CC04  58    MEMBER OF THE ASSEMBLY       58TH DISTRICT                                      
057VN04  58    VOTER NOMINATED                                                                 
057BK04  58                                                                                    
057CN04  58       CRISTINA GARCIA        DEM                                   138     2.75    
057CN04  58       MIGUEL A ALVARADO      DEM                                   271     5.41    
057CN04  58       IVAN ALTAMIRANO        DEM                                   428     8.54    
057CN04  58       PEDRO ACEITUNO         DEM                                   558    11.13    
057CN04  58       KARLA V SALAZAR        DEM                                   698    13.92    
057CN04  58       MIKE SIMPFENDERFER     REP                                   844    16.84    
057CN04  58       JOHN PAUL DRAYER       DEM                                   960    19.15    
057CN04  58       FRINE MEDRANO          DEM                                 1,116    22.26    
057BK04  58                                                                                    
057PR04  58    TOTAL PRECINCTS        213            PRECINCTS REPORTING       213      100    
057DR04  58    REGISTRATION       229,273                                                      
058CC04  59    MEMBER OF THE ASSEMBLY       59TH DISTRICT                                      
058VN04  59    VOTER NOMINATED                                                                 
058BK04  59                                                                                    
058CN04  59       R JONES-SAWYER         DEM                                    49    34.75    
058CN04  59       L HAGAN-MORGAN         DEM                                    92    65.25    
058BK04  59                                                                                    
058PR04  59    TOTAL PRECINCTS        170            PRECINCTS REPORTING       170      100    
058DR04  59    REGISTRATION       194,290                                                      
059CC04  62    MEMBER OF THE ASSEMBLY       62ND DISTRICT                                      
059VN04  62    VOTER NOMINATED                                                                 
059BK04  62                                                                                    
059CN04  62       AUTUMN BURKE           DEM                                    52    34.21    
059CN04  62       AL L HERNANDEZ         REP                                   100    65.79    
059BK04  62                                                                                    
059PR04  62    TOTAL PRECINCTS        257            PRECINCTS REPORTING       257      100    
059DR04  62    REGISTRATION       260,541                                                      
060CC04  63    MEMBER OF THE ASSEMBLY       63RD DISTRICT                                      
060VN04  63    VOTER NOMINATED                                                                 
060BK04  63                                                                                    
060CN04  63       ANTHONY RENDON         DEM                                   129    17.53    
060CN04  63       MARIA D ESTRADA        DEM                                   235    31.93    
060CN04  63       ADAM JOSHUA MILLER     REP                                   372    50.54    
060BK04  63                                                                                    
060PR04  63    TOTAL PRECINCTS        177            PRECINCTS REPORTING       177      100    
060DR04  63    REGISTRATION       203,593                                                      
061CC04  64    MEMBER OF THE ASSEMBLY       64TH DISTRICT                                      
061VN04  64    VOTER NOMINATED                                                                 
061BK04  64                                                                                    
061CN04  64       MIKE A GIPSON          DEM                                    81      100    
061BK04  64                                                                                    
061PR04  64    TOTAL PRECINCTS        221            PRECINCTS REPORTING       221      100    
061DR04  64    REGISTRATION       231,956                                                      
062CC04  66    MEMBER OF THE ASSEMBLY       66TH DISTRICT                                      
062VN04  66    VOTER NOMINATED                                                                 
062BK04  66                                                                                    
062CN04  66       CANEY ARNOLD           DEM                                    21    15.22    
062CN04  66       FRANK A SCOTTO         REP                                    48    34.78    
062CN04  66       AL MURATSUCHI          DEM                                    69     50.0    
062BK04  66                                                                                    
062PR04  66    TOTAL PRECINCTS        231            PRECINCTS REPORTING       231      100    
062DR04  66    REGISTRATION       282,506                                                      
063CC04  70    MEMBER OF THE ASSEMBLY       70TH DISTRICT                                      
063VN04  70    VOTER NOMINATED                                                                 
063BK04  70                                                                                    
063CN04  70       RACHEL A BRUHNKE       GRN                                    63    10.13    
063CN04  70       ELLIOT R GONZALES      DEM                                   128    20.58    
063CN04  70       HONOR ROBSON           LIB                                   177    28.46    
063CN04  70       PATRICK O'DONNELL      DEM                                   254    40.84    
063BK04  70                                                                                    
063PR04  70    TOTAL PRECINCTS        230            PRECINCTS REPORTING       230      100    
063DR04  70    REGISTRATION       270,915                                                      
064CC04  45    MEMBER OF THE ASSEMBLY       45TH DIST TERM ENDS 12/18                          
064VN04  45    VOTER NOMINATED                                                                 
064BK04  45                                                                                    
064CN04  45       JUSTIN M CLARK         REP                                    46    31.94    
064CN04  45       JESSE GABRIEL          DEM                                    98    68.06    
064BK04  45                                                                                    
064PR04  45    TOTAL PRECINCTS        191            PRECINCTS REPORTING       191      100    
064DR04  45    REGISTRATION       264,705                                                      
065CC04  39    MEMBER OF THE ASSEMBLY       39TH DIST TERM ENDS 12/18                          
065VN04  39    VOTER NOMINATED                                                                 
065BK04  39                                                                                    
065CN04  39       LUZ MARIA RIVAS        DEM                                   165    36.42    
065CN04  39       RICARDO A BENITEZ      REP                                   288    63.58    
065BK04  39                                                                                    
065PR04  39    TOTAL PRECINCTS        173            PRECINCTS REPORTING       173      100    
065DR04  39    REGISTRATION       225,672                                                      
066CC04  44    MEMBER OF THE ASSEMBLY       44TH DISTRICT                                      
066VN04  44    VOTER NOMINATED                                                                 
066BK04  44                                                                                    
066CN04  44       R BALDWIN-KENNEDY      REP                                    13    18.31    
066CN04  44       JACQUI IRWIN           DEM                                    26    36.62    
066CN04  44       ROBERT ZELINSKY        DEM                                    32    45.07    
066BK04  44                                                                                    
066PR04  44    TOTAL PRECINCTS          6            PRECINCTS REPORTING         6      100    
066DR04  44    REGISTRATION         5,963                                                      
067CC00  03    SUPERINTENDENT OF            PUBLIC INSTRUCTION                                 
067BK00  03                                                                                    
067CN00  03       LILY PLOSKI                                                1,133    10.19    
067CN00  03       STEVEN IRELAND                                             2,208    19.86    
067CN00  03       TONY K THURMOND                                            3,361    30.22    
067CN00  03       MARSHALL TUCK                                              4,418    39.73    
067BK00  03                                                                                    
067PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
067DR00  03    REGISTRATION     5,131,286                                                      
068MC00  03    STATE MEASURE 68                                                                
068BK00  03                                                                                    
068MT00  03         68 - PARKS & ENVIRONMENT BONDS  - YES                      254    34.84    
068MT00  03              (MAJORITY OF VOTES CAST)   - NO                       475    65.16    
068BK00  03                                                                                    
068PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
068DR00  03    REGISTRATION     5,131,286                                                      
069MC00  03    STATE MEASURE 69                                                                
069BK00  03                                                                                    
069MT00  03         69 - TRANSPORTATION TAX & FEES  - YES                      254    34.84    
069MT00  03              (MAJORITY OF VOTES CAST)   - NO                       475    65.16    
069BK00  03                                                                                    
069PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
069DR00  03    REGISTRATION     5,131,286                                                      
070MC00  03    STATE MEASURE 70                                                                
070BK00  03                                                                                    
070MT00  03         70 - CAP & TRADE RESERVE FUND   - YES                      254    34.84    
070MT00  03              (MAJORITY OF VOTES CAST)   - NO                       475    65.16    
070BK00  03                                                                                    
070PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
070DR00  03    REGISTRATION     5,131,286                                                      
071MC00  03    STATE MEASURE 71                                                                
071BK00  03                                                                                    
071MT00  03         71 - BALLOT MEASURES EFF. DATE  - YES                      254    34.84    
071MT00  03              (MAJORITY OF VOTES CAST)   - NO                       475    65.16    
071BK00  03                                                                                    
071PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
071DR00  03    REGISTRATION     5,131,286                                                      
072MC00  03    STATE MEASURE 72                                                                
072BK00  03                                                                                    
072MT00  03         72 - RAINWATER CAPTURE SYSTEMS  - YES                      254    34.84    
072MT00  03              (MAJORITY OF VOTES CAST)   - NO                       475    65.16    
072BK00  03                                                                                    
072PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
072DR00  03    REGISTRATION     5,131,286                                                      
073CC00  03    SHERIFF                                                                         
073BK00  03                                                                                    
073CN00  03       ROBERT LINDSEY                                               955    16.85    
073CN00  03       ALEX VILLANUEVA                                            1,880    33.17    
073CN00  03       JIM MCDONNELL                                              2,833    49.98    
073BK00  03                                                                                    
073PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
073DR00  03    REGISTRATION     5,131,286                                                      
074CC05  01    SUPERVISOR-1ST DISTRICT                                                         
074BK05  01                                                                                    
074CN05  01       HILDA L SOLIS                                                224      100    
074BK05  01                                                                                    
074PR05  01    TOTAL PRECINCTS        756            PRECINCTS REPORTING       756      100    
074DR05  01    REGISTRATION       852,698                                                      
075CC05  03    SUPERVISOR-3RD DISTRICT                                                         
075BK05  03                                                                                    
075CN05  03       ERIC PREVEN                                                  223    17.25    
075CN05  03       SHEILA KUEHL                                                 408    31.55    
075CN05  03       DANIEL G GLASER                                              662    51.20    
075BK05  03                                                                                    
075PR05  03    TOTAL PRECINCTS        867            PRECINCTS REPORTING       867      100    
075DR05  03    REGISTRATION     1,110,853                                                      
076CC00  03    JUDGE-SUPERIOR COURT         OFFICE NO 113                                      
076BK00  03                                                                                    
076CN00  03       JAVIER PEREZ                                               1,105    16.96    
076CN00  03       STEVEN SCHREINER                                           2,157    33.10    
076CN00  03       MICHAEL P RIBONS                                           3,255    49.95    
076BK00  03                                                                                    
076PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
076DR00  03    REGISTRATION     5,131,286                                                      
077CC00  03    JUDGE-SUPERIOR COURT         OFFICE NO 118                                      
077BK00  03                                                                                    
077CN00  03       TROY DAVIS                                                   811    34.15    
077CN00  03       DAVID D DIAMOND                                            1,564    65.85    
077BK00  03                                                                                    
077PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
077DR00  03    REGISTRATION     5,131,286                                                      
078CC00  03    JUDGE-SUPERIOR COURT         OFFICE NO 146                                      
078BK00  03                                                                                    
078CN00  03       EMILY T SPEAR                                                811    34.15    
078CN00  03       ARMANDO DURON                                              1,564    65.85    
078BK00  03                                                                                    
078PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
078DR00  03    REGISTRATION     5,131,286                                                      
079CC00  03    JUDGE-SUPERIOR COURT         OFFICE NO 16                                       
079BK00  03                                                                                    
079CN00  03       HUBERT S YUN                                               1,004    16.86    
079CN00  03       PATRICIA HUNTER                                            1,972    33.11    
079CN00  03       SYDNE JANE MICHEL                                          2,980    50.03    
079BK00  03                                                                                    
079PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
079DR00  03    REGISTRATION     5,131,286                                                      
080CC00  03    JUDGE-SUPERIOR COURT         OFFICE NO 20                                       
080BK00  03                                                                                    
080CN00  03       WENDY SEGALL                                                 890    33.81    
080CN00  03       MARY ANN ESCALANTE                                         1,742    66.19    
080BK00  03                                                                                    
080PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
080DR00  03    REGISTRATION     5,131,286                                                      
081CC00  03    JUDGE-SUPERIOR COURT         OFFICE NO 4                                        
081BK00  03                                                                                    
081CN00  03       A VERONICA SAUCEDA                                         1,009    16.90    
081CN00  03       MATTHEW SCHONBRUN                                          1,975    33.08    
081CN00  03       ALFRED A COLETTA                                           2,986    50.02    
081BK00  03                                                                                    
081PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
081DR00  03    REGISTRATION     5,131,286                                                      
082CC00  03    JUDGE-SUPERIOR COURT         OFFICE NO 60                                       
082BK00  03                                                                                    
082CN00  03       TONY J CHO                                                   961    16.88    
082CN00  03       BEN COLELLA                                                1,885    33.11    
082CN00  03       HOLLY L HANCOCK                                            2,848    50.02    
082BK00  03                                                                                    
082PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
082DR00  03    REGISTRATION     5,131,286                                                      
083CC00  03    JUDGE-SUPERIOR COURT         OFFICE NO 63                                       
083BK00  03                                                                                    
083CN00  03       ANTHONY LEWIS                                                880    33.81    
083CN00  03       MALCOLM H MACKEY                                           1,723    66.19    
083BK00  03                                                                                    
083PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
083DR00  03    REGISTRATION     5,131,286                                                      
084CC00  03    JUDGE-SUPERIOR COURT         OFFICE NO 67                                       
084BK00  03                                                                                    
084CN00  03       DENNIS P VINCENT                                           1,105    16.96    
084CN00  03       MARIA L ARMENDARIZ                                         2,157    33.10    
084CN00  03       ONICA VALLE COLE                                           3,255    49.95    
084BK00  03                                                                                    
084PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
084DR00  03    REGISTRATION     5,131,286                                                      
085CC00  03    JUDGE-SUPERIOR COURT         OFFICE NO 71                                       
085BK00  03                                                                                    
085CN00  03       DAVID A BERGER                                               811    34.15    
085CN00  03       DANIELLE R GIBBONS                                         1,564    65.85    
085BK00  03                                                                                    
085PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
085DR00  03    REGISTRATION     5,131,286                                                      
086CC00  03    JUDGE-SUPERIOR COURT         OFFICE NO 126                                      
086BK00  03                                                                                    
086CN00  03       RENE C GILBERTSON                                          1,105    16.96    
086CN00  03       SHLOMO FRIEMAN                                             2,157    33.10    
086CN00  03       KEN FULLER                                                 3,255    49.95    
086BK00  03                                                                                    
086PR00  03    TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
086DR00  03    REGISTRATION     5,131,286                                                      
087MC08  BU    BURBANK CITY SPECIAL MUNI    MEASURE T                                          
087BK08  BU                                                                                    
087MT08  BU          T - CONTINUE BWP 7% TRANSFER   - YES                        4    26.67    
087MT08  BU              (MAJORITY OF VOTES CAST)   - NO                        11    73.33    
087BK08  BU                                                                                    
087PR08  BU    TOTAL PRECINCTS         48            PRECINCTS REPORTING        48      100    
087DR08  BU    REGISTRATION        66,297                                                      
088MC08  BU    BURBANK CITY SPECIAL MUNI    MEASURE V                                          
088BK08  BU                                                                                    
088MT08  BU          V - CITY ELEC CHRTR  AMENDMENT - YES                        4    26.67    
088MT08  BU              (MAJORITY OF VOTES CAST)   - NO                        11    73.33    
088BK08  BU                                                                                    
088PR08  BU    TOTAL PRECINCTS         48            PRECINCTS REPORTING        48      100    
088DR08  BU    REGISTRATION        66,297                                                      
089MC08  BU    BURBANK CITY SPECIAL MUNI    MEASURE Y                                          
089BK08  BU                                                                                    
089MT08  BU          Y - BUSD ELEC CHRTR AMENDMENT  - YES                        4    26.67    
089MT08  BU              (MAJORITY OF VOTES CAST)   - NO                        11    73.33    
089BK08  BU                                                                                    
089PR08  BU    TOTAL PRECINCTS         48            PRECINCTS REPORTING        48      100    
089DR08  BU    REGISTRATION        66,297                                                      
090MC08  CH    CLAREMONT CITY SPEC MUNI     MEASURE SC                                         
090BK08  CH                                                                                    
090MT08  CH         SC - NEW POLICE FACILITY BONDS  - YES                       29    34.12    
090MT08  CH              (2/3 OF VOTES CAST)        - NO                        56    65.88    
090BK08  CH                                                                                    
090PR08  CH    TOTAL PRECINCTS         13            PRECINCTS REPORTING        13      100    
090DR08  CH    REGISTRATION        21,086                                                      
091MC08  GL    GLENDALE CITY SPEC MUNI      MEASURE P                                          
091BK08  GL                                                                                    
091MT08  GL          P - CITY ELEC CHRTR  AMENDMENT - YES                      156    34.67    
091MT08  GL              (MAJORITY OF VOTES CAST)   - NO                       294    65.33    
091BK08  GL                                                                                    
091PR08  GL    TOTAL PRECINCTS         80            PRECINCTS REPORTING        80      100    
091DR08  GL    REGISTRATION       105,342                                                      
092MC08  HU    HUNTINGTON PARK CITY SPEC    MEASURE S                                          
092BK08  HU                                                                                    
092MT08  HU          S - RAISE SALES TAX BY 1 CENT  - YES                       27    32.53    
092MT08  HU              (MAJORITY OF VOTES CAST)   - NO                        56    67.47    
092BK08  HU                                                                                    
092PR08  HU    TOTAL PRECINCTS         16            PRECINCTS REPORTING        16      100    
092DR08  HU    REGISTRATION        19,494                                                      
093MC08  IN    INGLEWOOD CITY SPEC MUNI     MEASURE SE                                         
093BK08  IN                                                                                    
093MT08  IN         SE - CITY ELEC CHRTR  AMENDMENT - YES                        6     50.0    
093MT08  IN              (MAJORITY OF VOTES CAST)   - NO                         6     50.0    
093BK08  IN                                                                                    
093PR08  IN    TOTAL PRECINCTS         62            PRECINCTS REPORTING        62      100    
093DR08  IN    REGISTRATION        60,053                                                      
094MC08  LO    LONG BEACH CITY SPEC MUNI    MEASURE M                                          
094BK08  LO                                                                                    
094MT08  LO          M - UTILITY REVENUE TRANSFER   - YES                        1    14.29    
094MT08  LO              (MAJORITY OF VOTES CAST)   - NO                         6    85.71    
094BK08  LO                                                                                    
094PR08  LO    TOTAL PRECINCTS        221            PRECINCTS REPORTING       221      100    
094DR08  LO    REGISTRATION       259,282                                                      
095MC08  MI    MONROVIA CITY SPECIAL MUNI   MEASURE TT                                         
095BK08  MI                                                                                    
095MT08  MI         TT - RAISE TRANSIENT OCCUP TAX  - YES                        8    44.44    
095MT08  MI              (MAJORITY OF VOTES CAST)   - NO                        10    55.56    
095BK08  MI                                                                                    
095PR08  MI    TOTAL PRECINCTS         17            PRECINCTS REPORTING        17      100    
095DR08  MI    REGISTRATION        20,296                                                      
096MC08  PS    PASADENA CITY SPECIAL MUNI   MEASURE AA                                         
096BK08  PS                                                                                    
096MT08  PS         AA - CITY ELEC CHRTR  AMENDMENT - YES                       51    32.48    
096MT08  PS              (MAJORITY OF VOTES CAST)   - NO                       106    67.52    
096BK08  PS                                                                                    
096PR08  PS    TOTAL PRECINCTS         60            PRECINCTS REPORTING        60      100    
096DR08  PS    REGISTRATION        81,215                                                      
097MC08  PS    PASADENA CITY SPECIAL MUNI   MEASURE CC                                         
097BK08  PS                                                                                    
097MT08  PS         CC - REPEAL CANNABIS BUS. BAN   - YES                       51    32.48    
097MT08  PS              (MAJORITY OF VOTES CAST)   - NO                       106    67.52    
097BK08  PS                                                                                    
097PR08  PS    TOTAL PRECINCTS         60            PRECINCTS REPORTING        60      100    
097DR08  PS    REGISTRATION        81,215                                                      
098MC08  PS    PASADENA CITY SPECIAL MUNI   MEASURE DD                                         
098BK08  PS                                                                                    
098MT08  PS         DD - CANNABIS BUSINESS TAX      - YES                       51    32.48    
098MT08  PS              (MAJORITY OF VOTES CAST)   - NO                       106    67.52    
098BK08  PS                                                                                    
098PR08  PS    TOTAL PRECINCTS         60            PRECINCTS REPORTING        60      100    
098DR08  PS    REGISTRATION        81,215                                                      
099CC08  RL    ROLLING HILLS EST CITY GEN   COUNCILMEMBER                                      
099VF08  RL    VOTE FOR NO MORE THAN   2                                                       
099BK08  RL                                                                                    
099CN08  RL       STEVEN ZUCKERMAN                                              11    14.47    
099CN08  RL       BRITT HUFF                                                    25    32.89    
099CN08  RL       ROBERT MEDAWAR                                                40    52.63    
099BK08  RL                                                                                    
099PR08  RL    TOTAL PRECINCTS          6            PRECINCTS REPORTING         6      100    
099DR08  RL    REGISTRATION         5,631                                                      
100MC08  RL    ROLLING HILLS EST CITY SPC   MEASURE A                                          
100BK08  RL                                                                                    
100MT08  RL          A - REVISE BUS. LICENSE TAX    - YES                       11    30.56    
100MT08  RL              (MAJORITY OF VOTES CAST)   - NO                        25    69.44    
100BK08  RL                                                                                    
100PR08  RL    TOTAL PRECINCTS          6            PRECINCTS REPORTING         6      100    
100DR08  RL    REGISTRATION         5,631                                                      
101MC08  TE    TEMPLE CITY SPECIAL MUNI     MEASURE VP                                         
101BK08  TE                                                                                    
101MT08  TE         VP - CITY ELEC CHRTR  AMENDMENT - YES                       33    35.87    
101MT08  TE              (MAJORITY OF VOTES CAST)   - NO                        59    64.13    
101BK08  TE                                                                                    
101PR08  TE    TOTAL PRECINCTS         14            PRECINCTS REPORTING        14      100    
101DR08  TE    REGISTRATION        16,791                                                      
102CC08  TR    TORRANCE CITY GEN MUNI       MAYOR                                              
102BK08  TR                                                                                    
102CN08  TR       TOM BREWER                                                    58    17.06    
102CN08  TR       RON RIGGS                                                    111    32.65    
102CN08  TR       PAT FUREY                                                    171    50.29    
102BK08  TR                                                                                    
102PR08  TR    TOTAL PRECINCTS         67            PRECINCTS REPORTING        67      100    
102DR08  TR    REGISTRATION        82,484                                                      
103CC08  TR    TORRANCE CITY GEN MUNI       COUNCILMEMBER                                      
103VF08  TR    VOTE FOR NO MORE THAN   3                                                       
103BK08  TR                                                                                    
103CN08  TR       JIMMY GOW                                                     58     4.87    
103CN08  TR       TIM GOODRICH                                                 111     9.32    
103CN08  TR       KURT WEIDEMAN                                                171    14.36    
103CN08  TR       BILL SUTHERLAND                                              239    20.07    
103CN08  TR       GEORGE CHEN                                                  282    23.68    
103CN08  TR       AURELIO MATTUCCI                                             330    27.71    
103BK08  TR                                                                                    
103PR08  TR    TOTAL PRECINCTS         67            PRECINCTS REPORTING        67      100    
103DR08  TR    REGISTRATION        82,484                                                      
104CC08  TR    TORRANCE CITY GEN MUNI       CITY CLERK                                         
104BK08  TR                                                                                    
104CN08  TR       REBECCA POIRIER                                               58      100    
104BK08  TR                                                                                    
104PR08  TR    TOTAL PRECINCTS         67            PRECINCTS REPORTING        67      100    
104DR08  TR    REGISTRATION        82,484                                                      
105CC08  TR    TORRANCE CITY GEN MUNI       CITY TREASURER                                     
105BK08  TR                                                                                    
105CN08  TR       DANA CORTEZ                                                   58      100    
105BK08  TR                                                                                    
105PR08  TR    TOTAL PRECINCTS         67            PRECINCTS REPORTING        67      100    
105DR08  TR    REGISTRATION        82,484                                                      
106MC11  45    BEVERLY HILLS UNIFIED SPC    MEASURE BH                                         
106BK11  45                                                                                    
106MT11  45         BH - SCHOOL IMPROVEMENT BONDS   - YES                       39    32.23    
106MT11  45              (55% OF VOTES CAST)        - NO                        82    67.77    
106BK11  45                                                                                    
106PR11  45    TOTAL PRECINCTS         21            PRECINCTS REPORTING        21      100    
106DR11  45    REGISTRATION        20,245                                                      
107CC10  28  1 PASADENA AREA COMM COLLEGE   GOV BD MEMBER TR AREA 1                            
107BK10  28  1                                                                                 
107CN10  28  1    ROSS S SELVIDGE                                                4     40.0    
107CN10  28  1    SANDRA CHEN LAU                                                6     60.0    
107BK10  28  1                                                                                 
107PR10  28  1 TOTAL PRECINCTS         44            PRECINCTS REPORTING        44      100    
107DR10  28  1 REGISTRATION        42,592                                                      
108CC10  28  3 PASADENA AREA COMM COLLEGE   GOV BD MEMBER TR AREA 3                            
108BK10  28  3                                                                                 
108CN10  28  3    BERLINDA J BROWN                                              38    35.19    
108CN10  28  3    ROGER E MARTINEZ                                              70    64.81    
108BK10  28  3                                                                                 
108PR10  28  3 TOTAL PRECINCTS         22            PRECINCTS REPORTING        22      100    
108DR10  28  3 REGISTRATION        29,705                                                      
109MC13  35    HAWTHORNE SCHOOL SPC         MEASURE HSD                                        
109BK13  35                                                                                    
109MT13  35        HSD - SCHOOL IMPROVEMENT BONDS   - YES                        3     50.0    
109MT13  35              (55% OF VOTES CAST)        - NO                         3     50.0    
109BK13  35                                                                                    
109PR13  35    TOTAL PRECINCTS         29            PRECINCTS REPORTING        29      100    
109DR13  35    REGISTRATION        28,843                                                      
110MC13  72    LITTLE LAKE CTY SCH SPC      MEASURE LL                                         
110BK13  72                                                                                    
110MT13  72         LL - EXTEND SCHOOL PARCEL TAX   - YES                       24    31.58    
110MT13  72              (2/3 OF VOTES CAST)        - NO                        52    68.42    
110BK13  72                                                                                    
110PR13  72    TOTAL PRECINCTS         18            PRECINCTS REPORTING        18      100    
110DR13  72    REGISTRATION        18,297                                                      
111MC11  42    MANHATTAN BEACH USD SPEC     MEASURE MB                                         
111BK11  42                                                                                    
111MT11  42         MB - SCHOOL PARCEL TAX          - YES                       42    31.82    
111MT11  42              (2/3 OF VOTES CAST)        - NO                        90    68.18    
111BK11  42                                                                                    
111PR11  42    TOTAL PRECINCTS         22            PRECINCTS REPORTING        22      100    
111DR11  42    REGISTRATION        25,038                                                      
112MC11  54    WISEBURN USD SPECIAL         MEASURE W                                          
112BK11  54                                                                                    
112MT11  54          W - SCHOOL IMPROVEMENT BONDS   - YES                        3    33.33    
112MT11  54              (55% OF VOTES CAST)        - NO                         6    66.67    
112BK11  54                                                                                    
112PR11  54    TOTAL PRECINCTS         14            PRECINCTS REPORTING        14      100    
112DR11  54    REGISTRATION         8,804                                                      
113MC11  36    INGLEWOOD UNIFIED SCH SPC    MEASURE ID                                         
113BK11  36                                                                                    
113MT11  36         ID - IUSD ELEC CHRTR  AMENDMENT - YES                       18    38.30    
113MT11  36              (MAJORITY OF VOTES CAST)   - NO                        29    61.70    
113BK11  36                                                                                    
113PR11  36    TOTAL PRECINCTS         63            PRECINCTS REPORTING        63      100    
113DR11  36    REGISTRATION        64,330                                                      
114MC11  30    PASADENA UNIFIED SCH SPC     MEASURE BB                                         
114BK11  30                                                                                    
114MT11  30         BB - PUSD ELEC CHRTR  AMENDMENT - YES                       84    32.94    
114MT11  30              (MAJORITY OF VOTES CAST)   - NO                       171    67.06    
114BK11  30                                                                                    
114PR11  30    TOTAL PRECINCTS         94            PRECINCTS REPORTING        94      100    
114DR11  30    REGISTRATION       124,682                                                      
115PRSTAT      ELECTION STATISTICS                                                             
115BKSTAT                                                                                      
115PRSTAT      TOTAL PRECINCTS      4,357            PRECINCTS REPORTING     4,357      100    
115DRSTAT      REGISTRATION     5,131,286                                                      
115BKSTAT                                                                                      
115BCSTAT                                                   VOTE AT POLL   324,908             
115BCSTAT                                                   VOTE BY MAIL   364,385             
115BCSTAT                                           BALLOTS CAST/TURNOUT   689,293    13.43    
999EF2641      1076                                                                            